import type {
  ChildInput,
  ChildPlan,
  FamilyNeeds,
  FamilyPlan,
  FlatResource,
  ResourceGroup,
} from "./types";

/**
 * Eligibility engine — a pure-function port of the v2 `generate()` logic.
 * MUST produce identical results to v2 (verified by scripts/test-eligibility.ts).
 */

export function flattenGroups(groups: ResourceGroup[]): FlatResource[] {
  return groups.flatMap((g) => g.resources.map((r) => ({ ...r, _group: g.id })));
}

const ageOk = (r: FlatResource, a: number) => a >= r.minAge && a <= r.maxAge;

/** Broad "whole family" programs: unflagged, minAge 0, maxAge ≥ 18. */
const isFamilyWide = (r: FlatResource) =>
  r.minAge === 0 && r.maxAge >= 18 && r.flags.length === 0;

function dedupe(list: FlatResource[]): FlatResource[] {
  const seen: Record<string, 1> = {};
  const uniq: FlatResource[] = [];
  list.forEach((r) => {
    if (!seen[r.id]) {
      seen[r.id] = 1;
      uniq.push(r);
    }
  });
  return uniq;
}

export function buildPlan(
  flatResources: FlatResource[],
  input: {
    parent: string;
    contact: string;
    zip: string;
    children: ChildInput[];
    fam: FamilyNeeds;
  }
): FamilyPlan {
  const { parent, contact, zip, children, fam } = input;

  const familyWide = flatResources.filter(isFamilyWide);

  const childPlans: ChildPlan[] = children
    .filter((c) => c.age !== "")
    .map((c) => {
      const a = Number(c.age);
      const matched = flatResources.filter((r) => {
        // age-narrowed only; broad all-kids programs are shown family-wide
        if (r.flags.length === 0) return ageOk(r, a) && !isFamilyWide(r);
        if (r.flags.includes("disability")) return c.disability && ageOk(r, a);
        if (r.flags.includes("lgbtq")) return c.lgbtq && ageOk(r, a);
        if (r.flags.includes("immigrant")) return fam.immigrant && ageOk(r, a);
        return false;
      });
      return { child: c, programs: dedupe(matched) };
    });

  const famExtra = flatResources.filter(
    (r) =>
      (r.flags.includes("immigrant") && fam.immigrant) ||
      (fam.food && r.cat === "food")
  );
  const family = dedupe([...familyWide, ...famExtra]);

  return {
    childPlans,
    family,
    familyData: {
      parent,
      contact,
      zip,
      children: children.filter((c) => c.age !== ""),
      fam,
    },
  };
}

/** All unique programs across a plan; used for the Cowork export. */
export function uniquePlanPrograms(plan: FamilyPlan): FlatResource[] {
  return dedupe([...plan.childPlans.flatMap((cp) => cp.programs), ...plan.family]);
}

export function coworkReadyPrograms(plan: FamilyPlan): FlatResource[] {
  return uniquePlanPrograms(plan).filter((r) => r.basicInfoOnly);
}

/** Builds the Cowork task payload — identical shape to v2's export. */
export function buildCoworkPayload(plan: FamilyPlan, generatedAt: string) {
  const fd = plan.familyData;
  const programs = coworkReadyPrograms(plan).map((r) => {
    const matchedChild = plan.childPlans.find((cp) =>
      cp.programs.some((p) => p.id === r.id)
    )?.child;
    return {
      programName: r.name,
      url: r.url,
      forChild: matchedChild
        ? `${matchedChild.name || "(child)"}  age ${matchedChild.age}`
        : "whole family",
      suggestedFields: {
        "Child / Youth First Name": matchedChild?.name?.split(" ")[0] || "UNKNOWN",
        "Child / Youth Last Name":
          matchedChild?.name?.split(" ").slice(1).join(" ") || "UNKNOWN",
        "Child Age": matchedChild?.age ? String(matchedChild.age) : "UNKNOWN",
        "Parent / Guardian Name": fd.parent || "UNKNOWN",
        "Phone or Email": fd.contact || "UNKNOWN",
        "ZIP Code": fd.zip || "UNKNOWN",
        City: "Memphis",
        State: "TN",
      },
    };
  });

  return {
    _note:
      "Generated by Memphis Family Resource Guide. Cowork task: for each program, open the URL in Chrome, fill the suggestedFields, pause for user review before submitting, then mark done.",
    coworkTask:
      "Read this file. For each item in 'programs': (1) Open its URL in Chrome. (2) Fill in the form with the suggestedFields values. (3) STOP and show me what you have filled in before submitting. (4) Only submit after I explicitly say OK. (5) If any field is 'UNKNOWN' or the form asks for something not listed, ask me. Do not proceed past any step without my confirmation.",
    generated: generatedAt,
    family: {
      parentName: fd.parent || "UNKNOWN",
      contact: fd.contact || "UNKNOWN",
      zip: fd.zip || "UNKNOWN",
    },
    children: (fd.children || []).map((c) => ({
      name: c.name || "(unnamed)",
      age: c.age,
    })),
    programs,
  };
}
