import type { ResourceGroup } from "./types";

// ════════════════════════════════════════════════════════════
//  SEED DATA — complete v2 dataset. This is the source of truth
//  for scripts/seed.ts and the offline/DB-unavailable fallback.
// ════════════════════════════════════════════════════════════
export const SEED_GROUPS: ResourceGroup[] = [
  {
    id: "all", label: "ALL AGES", kind: "age", charStage: null, color: "#2d2b52", sortOrder: 0,
    resources: [
      { id: "mpl", name: "Memphis Public Library", cat: "education", minAge: 0, maxAge: 99, flags: [], serve: "online", basicInfoOnly: true,
        desc: "Free library card for all Shelby County residents. 18 locations, 1.7M items, 70K+ ebooks, 3,824 programs/yr, 646 free internet terminals.",
        how: "Apply online (13+) or in person with ID. memphislibrary.org", url: "https://www.memphislibrary.org/start-here/" },
      { id: "901", name: "901 Pass", cat: "enrichment", minAge: 0, maxAge: 99, flags: [], serve: "inperson",
        desc: "Free city pass: all community centers, aquatics & senior centers, plus free Memphis Zoo every Tuesday. Can double as a library card.",
        how: "Pick up at any library or city community center.", url: "https://www.memphislibrary.org/901-pass-library-card/" },
      { id: "211", name: "211 Tennessee (LINC 2-1-1)", cat: "health", minAge: 0, maxAge: 99, flags: [], serve: "online",
        desc: "Free 24/7 helpline routing families to every available service in Shelby County: food, housing, healthcare, childcare, utilities.",
        how: "Dial 2-1-1, anytime. Also linc.net.", url: "https://linc.net" },
      { id: "tenncare", name: "TennCare / CHIP", cat: "health", minAge: 0, maxAge: 18, flags: [], serve: "online",
        desc: "Tennessee Medicaid: free/low-cost health & dental for qualifying children and families. Doctor visits, prescriptions, mental health.",
        how: "benefits.tn.gov or 1-855-259-0701.", url: "https://www.tn.gov/tenncare" },
      { id: "foodbank", name: "Mid-South Food Bank", cat: "food", minAge: 0, maxAge: 99, flags: [], serve: "inperson",
        desc: "Food assistance through partner pantries (many at MSCS schools) and mobile distribution sites across Shelby County.",
        how: "Find nearest pantry at midsouthfoodbank.org or dial 2-1-1.", url: "https://midsouthfoodbank.org" },
      { id: "snap", name: "SNAP (Food Stamps)", cat: "food", minAge: 0, maxAge: 99, flags: [], serve: "online",
        desc: "Federal food-purchase assistance. 150K+ Shelby County residents benefit; ~40% of recipients are children.",
        how: "Apply at benefits.tn.gov or your local DHS office.", url: "https://www.tn.gov/humanservices/for-families/supplemental-nutrition-assistance-program.html" },
      { id: "progeny", name: "ProGeny Place — Connected & Empowered Digital Literacy", cat: "technology", minAge: 0, maxAge: 99, flags: [], serve: "navigator", basicInfoOnly: true,
        desc: "Free monthly hands-on digital-literacy workshops for all ages (with M Street Fiber & Ting): 6 modules from basic device use and online safety to email, resume-building, and career paths in e-commerce, remote work, and content creation. Complete the series and receive a computer to keep. [Verify program details locally.]",
        how: "RSVP at progenyplace.org/events. Email info@progenyplace.org · 901-701-6036.", url: "https://www.progenyplace.org/events-1/connected-empowered-digital-literacy" },
    ],
  },
  {
    id: "0-2", label: "BIRTH – AGE 2", kind: "age", charStage: 0, color: "#e07c45", sortOrder: 1,
    resources: [
      { id: "imag", name: "Books from Birth / Imagination Library", cat: "education", minAge: 0, maxAge: 5, flags: [], serve: "online", basicInfoOnly: true,
        desc: "Shelby County affiliate of Dolly Parton's Imagination Library (run by Porter-Leath). One free age-appropriate book mailed to your child each month, birth–age 5, in your child's name. No income requirement.",
        how: "Register at imaginationlibrary.com — select Shelby County.", url: "https://imaginationlibrary.com/usa/find-my-program/" },
      { id: "wic", name: "WIC — Women, Infants & Children", cat: "health", minAge: 0, maxAge: 5, flags: [], serve: "inperson",
        desc: "Free food, formula, produce + nutrition counseling and healthcare referrals for pregnant women, new mothers, infants, and children under 5. Generous income guidelines.",
        how: "Shelby County Health Dept: 901-222-9100.", url: "https://www.shelbytnhealth.com/243/WIC" },
      { id: "warmline", name: "Le Bonheur Parent Support Warm Line", cat: "health", minAge: 0, maxAge: 18, flags: [], serve: "online",
        desc: "Free phone line staffed by Le Bonheur professionals: parenting questions, child-development concerns, resource connections. Not a crisis line.",
        how: "Call 844-877-9276, Mon–Fri 11am–8pm.", url: "https://lebonheur.org" },
      { id: "ehs", name: "Early Head Start (Porter-Leath)", cat: "education", minAge: 0, maxAge: 3, flags: [], serve: "navigator",
        desc: "Federally-funded comprehensive services for income-eligible families: early education, health screenings, nutrition, parent support, birth–age 3.",
        how: "porterleath.org or 901-320-0591.", url: "https://www.porterleath.org" },
      { id: "uci", name: "Urban Child Institute", cat: "education", minAge: 0, maxAge: 3, flags: [], serve: "online",
        desc: "Memphis nonprofit with research, guides, and resource connections for parents of children under 3 — the most critical developmental window.",
        how: "Free resources at urbanchildinstitute.org.", url: "https://www.urbanchildinstitute.org" },
    ],
  },
  {
    id: "3-5", label: "AGES 3–5", kind: "age", charStage: 1, color: "#3aab7c", sortOrder: 2,
    resources: [
      { id: "prek", name: "First 8 Memphis / Pre-K for All", cat: "education", minAge: 3, maxAge: 4, flags: [], serve: "inperson",
        desc: "2025 ordinance: free Pre-K for ALL 3–4 year-olds in Shelby County, regardless of income. 97+ classrooms, with wraparound health, nutrition & family support.",
        how: "Apply at first8memphis.org or scsk12.org/prek.", url: "https://www.first8memphis.org/pre-k-registration" },
      { id: "mscs-prek", name: "MSCS Early Childhood Program", cat: "education", minAge: 3, maxAge: 4, flags: [], serve: "inperson",
        desc: "Memphis-Shelby County Schools Pre-K at select elementaries and Early Learning Centers. 3,340+ students/yr; strong kindergarten-readiness outcomes.",
        how: "scsk12.org/prek. Child must turn 3 or 4 by Aug 15.", url: "https://www.scsk12.org/prek/" },
      { id: "discoverread", name: "Library DiscoverREAD", cat: "education", minAge: 0, maxAge: 5, flags: [], serve: "navigator",
        desc: "Early-literacy programming at all branches: story times, STEAM activities, school-readiness events. Free, mostly walk-in.",
        how: "memphislibrary.org/events → filter Children's.", url: "https://memphislibrary.org" },
      { id: "hs", name: "Head Start (Porter-Leath)", cat: "education", minAge: 3, maxAge: 4, flags: [], serve: "navigator",
        desc: "Federal full-day program for income-eligible 3–4 year-olds: education, health, dental, nutrition, family services — most comprehensive early-childhood option.",
        how: "porterleath.org. Income guidelines apply.", url: "https://www.porterleath.org" },
    ],
  },
  {
    id: "6-11", label: "AGES 6–11", kind: "age", charStage: 2, color: "#4a7fcf", sortOrder: 3,
    resources: [
      { id: "summerread", name: "Library Summer Reading", cat: "education", minAge: 5, maxAge: 18, flags: [], serve: "inperson",
        desc: "Free annual summer reading program across all 18 branches. Reduces summer learning loss, especially for low-income students.",
        how: "Sign up at any branch each summer.", url: "https://memphislibrary.org" },
      { id: "zoo", name: "Memphis Zoo — Free Tuesdays", cat: "enrichment", minAge: 0, maxAge: 99, flags: [], serve: "inperson",
        desc: "Free every Tuesday for residents with a 901 Pass. One of the best recurring free family outings in the city.",
        how: "Get a 901 Pass, bring it Tuesdays.", url: "https://memphiszoo.org" },
      { id: "bgc", name: "Boys & Girls Club of Greater Memphis", cat: "enrichment", minAge: 6, maxAge: 18, flags: [], serve: "navigator",
        desc: "After-school and summer programs: academic support, sports, arts, character development. Multiple locations; consistent attendance improves outcomes.",
        how: "Enroll at bgcmemphis.org.", url: "https://www.bgcmemphis.org" },
      { id: "ymca", name: "YMCA of Memphis & the Mid-South", cat: "enrichment", minAge: 0, maxAge: 18, flags: [], serve: "navigator",
        desc: "After-school care, summer camp, swim lessons, sports leagues. Financial assistance available — no one is turned away for inability to pay.",
        how: "ymcamemphis.org or any Y branch.", url: "https://ymcamemphis.org" },
      { id: "bbbs", name: "Big Brothers Big Sisters of the Mid-South", cat: "enrichment", minAge: 6, maxAge: 17, flags: [], serve: "navigator", basicInfoOnly: true,
        desc: "Free one-on-one mentorship matching kids 6–17 with vetted adult volunteers. School- and community-based matches.",
        how: "Apply at bbbsmidsouth.org.", url: "https://www.bbbsmidsouth.org" },
      { id: "schoolpantry", name: "MSCS School Food Pantries", cat: "food", minAge: 4, maxAge: 18, flags: [], serve: "inperson",
        desc: "Many Memphis-Shelby County schools run weekly/monthly food pantries; some partner with Mid-South Food Bank for mobile distribution.",
        how: "Contact your school's Family Engagement staff. No documentation needed.", url: "https://www.scsk12.org" },
    ],
  },
  {
    id: "12-16", label: "AGES 12–16", kind: "age", charStage: 3, color: "#9b59b6", sortOrder: 4,
    resources: [
      { id: "cloud901", name: "CLOUD901 Teen Learning Lab", cat: "technology", minAge: 12, maxAge: 18, flags: [], serve: "inperson",
        desc: "State-of-the-art teen tech & creativity space at the Central Library (3030 Poplar). Design, media, learning programs for teens.",
        how: "Drop in at Central Library. Free.", url: "https://memphislibrary.org" },
      { id: "teeninnov", name: "Library Teen Innovation Centers", cat: "technology", minAge: 12, maxAge: 18, flags: [], serve: "inperson",
        desc: "3D printing, digital media, coding, and music production at select branches. Free with a library card.",
        how: "Check memphislibrary.org/events for locations.", url: "https://memphislibrary.org" },
      { id: "udemy", name: "Udemy via Memphis Library (Free)", cat: "technology", minAge: 13, maxAge: 99, flags: [], serve: "online",
        desc: "Free access to thousands of Udemy professional courses through the library's Gale Presents program — business, tech, design, languages.",
        how: "Get a library card → memphislibrary.org → Learn → Computers → Udemy.", url: "https://www.memphislibrary.org/learn/computers/" },
      { id: "joblinc", name: "JobLINC at Central Library", cat: "technology", minAge: 14, maxAge: 99, flags: [], serve: "inperson",
        desc: "Free career coaching, resume review, mock interviews, digital job-seeking skills. Free computers and printers.",
        how: "Walk in at Central Library, 3030 Poplar.", url: "https://memphislibrary.org" },
      { id: "swcc-dl", name: "SW Tennessee CC — Free Digital Literacy", cat: "technology", minAge: 16, maxAge: 99, flags: [], serve: "navigator",
        desc: "Free non-credit digital-literacy & Microsoft Office courses via TN Board of Regents. Info sessions in Jan & Aug.",
        how: "southwest.tn.edu for session dates.", url: "https://www.southwest.tn.edu" },
    ],
  },
  {
    id: "17-18", label: "AGES 17–18", kind: "age", charStage: 4, color: "#f4645f", sortOrder: 5,
    resources: [
      { id: "tnpromise", name: "Tennessee Promise", cat: "education", minAge: 17, maxAge: 18, flags: [], serve: "online",
        desc: "EVERY TN public-school senior is eligible for two years of tuition-free community or technical college. Last-dollar scholarship, no income limit.",
        how: "Apply at tnpromise.gov in fall of senior year. Deadline Nov 1.", url: "https://tnpromise.gov" },
      { id: "fafsa", name: "FAFSA — Federal Student Aid", cat: "education", minAge: 16, maxAge: 18, flags: [], serve: "online",
        desc: "Unlocks Pell Grants (up to ~$7K/yr free), subsidized loans, work-study. Free to file. Opens Oct 1. Never pay anyone to complete it.",
        how: "studentaid.gov. Needs parent tax info for dependents.", url: "https://studentaid.gov" },
      { id: "tsaa", name: "TN Student Assistance Award (TSAA)", cat: "education", minAge: 17, maxAge: 18, flags: [], serve: "online",
        desc: "State need-based grant; stacks on top of Tennessee Promise for extra support.",
        how: "File FAFSA first; see tn.gov/collegepays.", url: "https://www.tn.gov/collegepays/money-for-college/tn-education-lottery-programs/tennessee-student-assistance-award.html" },
      { id: "swcc", name: "Southwest Tennessee Community College", cat: "education", minAge: 16, maxAge: 99, flags: [], serve: "online",
        desc: "Primary TN Promise destination in Memphis: certificates, associate degrees, transfer pathways, dual enrollment for current high-schoolers.",
        how: "Apply at southwest.tn.edu.", url: "https://www.southwest.tn.edu" },
    ],
  },
  // ── DEMOGRAPHIC / IDENTITY-SPECIFIC ──────────────────────────
  {
    id: "disability", label: "NEURODIVERGENT & DISABILITY", kind: "demo", charStage: null, color: "#16a085", sortOrder: 6,
    note: "Supports for children who are autistic, neurodivergent, or have developmental, learning, or physical disabilities. Newest section — verify details locally.",
    resources: [
      { id: "teis", name: "Tennessee Early Intervention System (TEIS)", cat: "health", minAge: 0, maxAge: 3, flags: ["disability"], serve: "navigator",
        desc: "Free voluntary program for children birth–3 with disabilities or developmental delay. Free evaluation and services for motor, communication, cognitive, social, and adaptive delays.",
        how: "1-800-852-7157 (West TN).", url: "https://www.tn.gov/didd/for-consumers/tennessee-early-intervention-system-teis.html" },
      { id: "lead", name: "Le Bonheur LEAD (Early Intervention & Development)", cat: "health", minAge: 0, maxAge: 3, flags: ["disability"], serve: "navigator",
        desc: "Birth–3 early intervention: PT, OT, speech-language, feeding/swallowing, audiology — in homes and child-care centers. Partners with TEIS.",
        how: "901-287-4900.", url: "https://www.lebonheur.org/services/services-for-children-with-special-needs" },
      { id: "arc", name: "The Arc Mid-South", cat: "identity", minAge: 0, maxAge: 18, flags: ["disability"], serve: "navigator",
        desc: "Advocacy, community outreach, and family support for people with intellectual and developmental disabilities.",
        how: "901-327-2473, thearcmidsouth.org.", url: "https://www.thearcmidsouth.org" },
      { id: "arms", name: "Autism Resources of the Mid-South (ARMS)", cat: "identity", minAge: 0, maxAge: 18, flags: ["disability"], serve: "navigator",
        desc: "Support, advocacy, and education for everyone affected by autism in the Mid-South.",
        how: "901-509-3027, autismresourcesmidsouth.org.", url: "https://autismresourcesmidsouth.org/" },
      { id: "step", name: "Support & Training for Exceptional Parents (STEP)", cat: "education", minAge: 0, maxAge: 18, flags: ["disability"], serve: "navigator",
        desc: "Tennessee's parent-training & information center. Free help understanding special-education rights and building your child's IEP.",
        how: "1-800-280-7837, tnstep.info.", url: "https://tnstep.info/" },
      { id: "boling", name: "Boling Center for Developmental Disabilities (UTHSC)", cat: "health", minAge: 0, maxAge: 18, flags: ["disability"], serve: "navigator",
        desc: "University center supporting children & families through evaluation, services, training, and research on developmental disabilities.",
        how: "901-448-6511.", url: "https://uthsc.edu/cdd/" },
      { id: "katiebeckett", name: "Katie Beckett Program (TennCare)", cat: "health", minAge: 0, maxAge: 18, flags: ["disability"], serve: "navigator",
        desc: "For children under 18 with disabilities or complex medical needs who don't qualify for Medicaid due to parental income/assets.",
        how: "tn.gov/didd → Katie Beckett.", url: "https://www.tn.gov/didd/katie-beckett-program.html" },
      { id: "pathfinder", name: "Tennessee Disability Pathfinder", cat: "identity", minAge: 0, maxAge: 18, flags: ["disability"], serve: "online",
        desc: "Statewide free directory + multilingual helpline connecting families to disability services of every kind.",
        how: "1-800-640-4636, tnpathfinder.org.", url: "https://www.tnpathfinder.org" },
    ],
  },
  {
    id: "lgbtq", label: "LGBTQ+ YOUTH", kind: "demo", charStage: null, color: "#8e44ad", sortOrder: 7,
    note: "Affirming community, support, and family services. Newest section — verify details locally.",
    resources: [
      { id: "prysm", name: "OUTMemphis — PRYSM Youth Program", cat: "identity", minAge: 12, maxAge: 17, flags: ["lgbtq"], serve: "navigator", basicInfoOnly: true,
        desc: "Proud, Resilient, Youth-Standing-Memphis: a supportive program for LGBTQ+ youth 12–17 building community, celebrating identity, and providing tools to thrive.",
        how: "Youth Empowerment Center, 2055 Southern Ave. outmemphis.org/prysm.", url: "https://www.outmemphis.org/prysm" },
      { id: "out-nav", name: "OUTMemphis — Family Care Navigation", cat: "identity", minAge: 0, maxAge: 18, flags: ["lgbtq"], serve: "navigator",
        desc: "Support for caregivers navigating their child's LGBTQ+ identity, plus care navigation for trans and gender-nonconforming youth and the whole family.",
        how: "outmemphis.org/services.", url: "https://www.outmemphis.org/services" },
    ],
  },
  {
    id: "immigrant", label: "IMMIGRANT, REFUGEE & CULTURAL COMMUNITIES", kind: "demo", charStage: null, color: "#d35400", sortOrder: 8,
    note: "Help with school enrollment, benefits, legal questions, and belonging for immigrant, refugee, and multilingual families. Verify details locally.",
    resources: [
      { id: "latino", name: "Latino Memphis", cat: "identity", minAge: 0, maxAge: 18, flags: ["immigrant"], serve: "navigator",
        desc: "Connects Latino families to education, health, and legal services. Navigators help with school enrollment, benefits, and immigration questions.",
        how: "latinomemphis.org.", url: "https://www.latinomemphis.org" },
      { id: "refugee-emp", name: "Refugee Empowerment Program", cat: "identity", minAge: 0, maxAge: 18, flags: ["immigrant"], serve: "navigator",
        desc: "Supports refugee and immigrant families through education, employment, and belonging programs as families rebuild new lives.",
        how: "Search 'Refugee Empowerment Program Memphis'.", url: "https://www.refugeeempowerment.com" },
      { id: "air", name: "Advocates for Immigrant Rights (AIR)", cat: "identity", minAge: 0, maxAge: 18, flags: ["immigrant"], serve: "navigator",
        desc: "Defends immigrants' rights and dignity through legal representation and advocacy, especially for those most at risk.",
        how: "Search 'Advocates for Immigrant Rights Memphis'.", url: "https://www.airtn.org" },
      { id: "vacwt", name: "Vietnamese American Community of West TN", cat: "identity", minAge: 0, maxAge: 18, flags: ["immigrant"], serve: "navigator",
        desc: "Preserves Vietnamese heritage in West Tennessee — culture, family support, and helping youth carry traditions forward.",
        how: "Search 'Vietnamese American Community West Tennessee'.", url: "" },
    ],
  },
  {
    id: "stem", label: "STEM & DIGITAL EQUITY", kind: "demo", charStage: null, color: "#2c82c9", sortOrder: 9,
    note: "Free tech, coding, and digital-skills programs widening access for underrepresented Memphis youth. Verify details locally.",
    resources: [
      { id: "codecrew", name: "CodeCrew", cat: "technology", minAge: 8, maxAge: 18, flags: [], serve: "navigator",
        desc: "Free coding education and mentorship for Memphis youth: after-school, summer camps, and the CodeSchool of Memphis. Focus on students underrepresented in tech.",
        how: "codecrew.org.", url: "https://www.codecrew.org" },
    ],
  },
];
